import { } from "../../types.js"

let initialState = {
    settings: {
        socialMedia: {
            facebook: 'https://facebook.com',
            instagram: 'https://instagram.com',
            telegram: 'https://telegram.org/',
            phones: ["+38 (098) 501 73 73", "+38 (073) 501 73 73", "+38 (050) 501 73 73", "+38 (044) 501 73 73"],
            date: 2023,
            email: "info@comtrading.ua",
            siteName: "comtrading"
        },
        timeWork: ["Пн. - Пт. з 09:00 до 19:00", "Сб. з 10:00 до 14:00", "Вс. - выходной"]
    },
    catalog:
        [
            {
                "id": 694584,
                "model": "AGMattFrameiP12Blue",
                "sku": "AGMattFrameiP12Blue",
                "name": "Чехол для смартфона AG Glass Matt Frame Color Logo for Apple iPhone 12 Navy Blue",
                "category_id": 508,
                "category_name": "Чехлы, накладки",
                "supl_price": 3.84,
                "price": 6.84,
                "margin": 3,
                "slug": "prod-chexol-dlya-smartfona-ag-glass-matt-frame-color-lo-694584",
                "image": "",
                "upc": "",
                "fix": false,
                "manufacturer_id": 1355,
                "stock": "В наличии"
            },
            {
                "id": 694583,
                "model": "AGMattFrameiP15LGreen",
                "sku": "AGMattFrameiP15LGreen",
                "name": "Чехол для смартфона AG Glass Matt Frame Color Logo for Apple iPhone 15 Light Green",
                "category_id": 508,
                "category_name": "Чехлы, накладки",
                "supl_price": 3.84,
                "price": 6.84,
                "margin": 3,
                "slug": "prod-chexol-dlya-smartfona-ag-glass-matt-frame-color-lo-694583",
                "image": "",
                "upc": "",
                "fix": false,
                "manufacturer_id": 1355,
                "stock": "В наличии"
            },
            {
                "id": 694582,
                "model": "AGMattFrameiP15PMGreen",
                "sku": "AGMattFrameiP15PMGreen",
                "name": "Чехол для смартфона AG Glass Matt Frame Color Logo for Apple iPhone 15 Pro Max Cangling Green",
                "category_id": 508,
                "category_name": "Чехлы, накладки",
                "supl_price": 3.84,
                "price": 6.84,
                "margin": 3,
                "slug": "prod-chexol-dlya-smartfona-ag-glass-matt-frame-color-lo-694582",
                "image": "",
                "upc": "",
                "fix": false,
                "manufacturer_id": 1355,
                "stock": "В наличии"
            },
            {
                "id": 694581,
                "model": "AGMattFrameiP11LBlue",
                "sku": "AGMattFrameiP11LBlue",
                "name": "Чехол для смартфона AG Glass Matt Frame Color Logo for Apple iPhone 11 Sierra Blue",
                "category_id": 508,
                "category_name": "Чехлы, накладки",
                "supl_price": 3.84,
                "price": 6.84,
                "margin": 3,
                "slug": "prod-chexol-dlya-smartfona-ag-glass-matt-frame-color-lo-694581",
                "image": "",
                "upc": "",
                "fix": false,
                "manufacturer_id": 1355,
                "stock": "В наличии"
            },
            {
                "id": 694580,
                "model": "AGMattFrameiP12LPurple",
                "sku": "AGMattFrameiP12LPurple",
                "name": "Чехол для смартфона AG Glass Matt Frame Color Logo for Apple iPhone 12 Light Purple",
                "category_id": 508,
                "category_name": "Чехлы, накладки",
                "supl_price": 3.84,
                "price": 6.84,
                "margin": 3,
                "slug": "prod-chexol-dlya-smartfona-ag-glass-matt-frame-color-lo-694580",
                "image": "",
                "upc": "",
                "fix": false,
                "manufacturer_id": 1355,
                "stock": "В наличии"
            },
            {
                "id": 694579,
                "model": "AGMattFrameiP12Green",
                "sku": "AGMattFrameiP12Green",
                "name": "Чехол для смартфона AG Glass Matt Frame Color Logo for Apple iPhone 12 Cangling Green",
                "category_id": 508,
                "category_name": "Чехлы, накладки",
                "supl_price": 3.84,
                "price": 6.84,
                "margin": 3,
                "slug": "prod-chexol-dlya-smartfona-ag-glass-matt-frame-color-lo-694579",
                "image": "",
                "upc": "",
                "fix": false,
                "manufacturer_id": 1355,
                "stock": "В наличии"
            },
            {
                "id": 694578,
                "model": "AGMattFrameMGiP13PDBlue",
                "sku": "AGMattFrameMGiP13PDBlue",
                "name": "Чехол для смартфона AG Glass Matt Frame Color MagSafe Logo for Apple iPhone 13 Pro Navy Blue",
                "category_id": 508,
                "category_name": "Чехлы, накладки",
                "supl_price": 4.78,
                "price": 7.78,
                "margin": 3,
                "slug": "prod-chexol-dlya-smartfona-ag-glass-matt-frame-color-ma-694578",
                "image": "",
                "upc": "",
                "fix": false,
                "manufacturer_id": 1355,
                "stock": "В наличии"
            },
            {
                "id": 694577,
                "model": "AGMattFrameiP11PBlack",
                "sku": "AGMattFrameiP11PBlack",
                "name": "Чехол для смартфона AG Glass Matt Frame Color Logo for Apple iPhone 11 Pro Graphite Black",
                "category_id": 508,
                "category_name": "Чехлы, накладки",
                "supl_price": 3.84,
                "price": 6.84,
                "margin": 3,
                "slug": "prod-chexol-dlya-smartfona-ag-glass-matt-frame-color-lo-694577",
                "image": "",
                "upc": "",
                "fix": false,
                "manufacturer_id": 1355,
                "stock": "В наличии"
            },
            {
                "id": 694576,
                "model": "BHR5380GL",
                "sku": "BHR5380GL",
                "name": "Смарт-годинник Xiaomi Watch S1 Active Black",
                "category_id": 491,
                "category_name": "Умные часы (Smartwatch)",
                "supl_price": 87.36,
                "price": 90.36,
                "margin": 3,
                "slug": "prod-smart-godinnik-xiaomi-watch-s1-active-black-694576",
                "image": "",
                "upc": "",
                "fix": false,
                "manufacturer_id": 9543,
                "stock": "В наличии"
            },
            {
                "id": 694575,
                "model": "UC310E-256G-RGN",
                "sku": "UC310E-256G-RGN",
                "name": "Flash A-DATA USB 3.2 UC310 Eco 256Gb Green",
                "category_id": 384,
                "category_name": "Флеш-накопители USB (флешки USB)",
                "supl_price": 13.52,
                "price": 16.52,
                "margin": 3,
                "slug": "prod-flash-a-data-usb-32-uc310-eco-256gb-green-694575",
                "image": "",
                "upc": "",
                "fix": false,
                "manufacturer_id": 11,
                "stock": "В наличии"
            },
            {
                "id": 694574,
                "model": "CosmicFXR12CAzure",
                "sku": "CosmicFXR12CAzure",
                "name": "Чехол для смартфона Cosmiс Full Case HQ 2mm for Xiaomi Redmi 12C Azure",
                "category_id": 508,
                "category_name": "Чехлы, накладки",
                "supl_price": 1.64,
                "price": 4.64,
                "margin": 3,
                "slug": "prod-chexol-dlya-smartfona-cosmis-full-case-hq-2mm-for--694574",
                "image": "",
                "upc": "",
                "fix": false,
                "manufacturer_id": 15097,
                "stock": "В наличии"
            },
            {
                "id": 694573,
                "model": "CosmicFPC40Mint",
                "sku": "CosmicFPC40Mint",
                "name": "Чехол для смартфона Cosmiс Full Case HQ 2mm for Poco C40 Mint",
                "category_id": 508,
                "category_name": "Чехлы, накладки",
                "supl_price": 1.64,
                "price": 4.64,
                "margin": 3,
                "slug": "prod-chexol-dlya-smartfona-cosmis-full-case-hq-2mm-for--694573",
                "image": "",
                "upc": "",
                "fix": false,
                "manufacturer_id": 15097,
                "stock": "В наличии"
            },
            {
                "id": 694572,
                "model": "CosmicFXR10CGreen",
                "sku": "CosmicFXR10CGreen",
                "name": "Чехол для смартфона Cosmiс Full Case HQ 2mm for Xiaomi Redmi 10C Green",
                "category_id": 508,
                "category_name": "Чехлы, накладки",
                "supl_price": 1.64,
                "price": 4.64,
                "margin": 3,
                "slug": "prod-chexol-dlya-smartfona-cosmis-full-case-hq-2mm-for--694572",
                "image": "",
                "upc": "",
                "fix": false,
                "manufacturer_id": 15097,
                "stock": "В наличии"
            },
            {
                "id": 694571,
                "model": "CDSHIiP12PMPurple",
                "sku": "CDSHIiP12PMPurple",
                "name": "Чехол для смартфона Cosmic CD Shiny Magnetic for Apple iPhone 12 Pro Max Purple",
                "category_id": 508,
                "category_name": "Чехлы, накладки",
                "supl_price": 2.34,
                "price": 5.34,
                "margin": 3,
                "slug": "prod-chexol-dlya-smartfona-cosmic-cd-shiny-magnetic-for-694571",
                "image": "",
                "upc": "",
                "fix": false,
                "manufacturer_id": 15097,
                "stock": "В наличии"
            },
            {
                "id": 694570,
                "model": "ClearColori15TrBlue",
                "sku": "ClearColori15TrBlue",
                "name": "Чехол для смартфона Cosmic Clear Color 2 mm for Apple iPhone 15 Transparent Blue",
                "category_id": 508,
                "category_name": "Чехлы, накладки",
                "supl_price": 1.3,
                "price": 4.3,
                "margin": 3,
                "slug": "prod-chexol-dlya-smartfona-cosmic-clear-color-2-mm-for--694570",
                "image": "",
                "upc": "",
                "fix": false,
                "manufacturer_id": 15097,
                "stock": "В наличии"
            },
            {
                "id": 694569,
                "model": "CoSoftPoM5sGreen",
                "sku": "CoSoftPoM5sGreen",
                "name": "Чехол для смартфона Cosmiс Soft Case Glass Cam for Poco M5s Green",
                "category_id": 508,
                "category_name": "Чехлы, накладки",
                "supl_price": 1.04,
                "price": 4.04,
                "margin": 3,
                "slug": "prod-chexol-dlya-smartfona-cosmis-soft-case-glass-cam-f-694569",
                "image": "",
                "upc": "",
                "fix": false,
                "manufacturer_id": 15097,
                "stock": "В наличии"
            },
            {
                "id": 694568,
                "model": "CDSHIiP12PDeepPurple",
                "sku": "CDSHIiP12PDeepPurple",
                "name": "Чехол для смартфона Cosmic CD Shiny Magnetic for Apple iPhone 12 Pro Deep Purple",
                "category_id": 508,
                "category_name": "Чехлы, накладки",
                "supl_price": 2.34,
                "price": 5.34,
                "margin": 3,
                "slug": "prod-chexol-dlya-smartfona-cosmic-cd-shiny-magnetic-for-694568",
                "image": "",
                "upc": "",
                "fix": false,
                "manufacturer_id": 15097,
                "stock": "В наличии"
            },
            {
                "id": 694567,
                "model": "CoSoftPoM5sLavender",
                "sku": "CoSoftPoM5sLavender",
                "name": "Чехол для смартфона Cosmiс Soft Case Glass Cam for Poco M5s Lavender Blue",
                "category_id": 508,
                "category_name": "Чехлы, накладки",
                "supl_price": 1.04,
                "price": 4.04,
                "margin": 3,
                "slug": "prod-chexol-dlya-smartfona-cosmis-soft-case-glass-cam-f-694567",
                "image": "",
                "upc": "",
                "fix": false,
                "manufacturer_id": 15097,
                "stock": "В наличии"
            },
            {
                "id": 694566,
                "model": "CDSHIiP13PMBlack",
                "sku": "CDSHIiP13PMBlack",
                "name": "Чехол для смартфона Cosmic CD Shiny Magnetic for Apple iPhone 13 Pro Max Black",
                "category_id": 508,
                "category_name": "Чехлы, накладки",
                "supl_price": 2.34,
                "price": 5.34,
                "margin": 3,
                "slug": "prod-chexol-dlya-smartfona-cosmic-cd-shiny-magnetic-for-694566",
                "image": "",
                "upc": "",
                "fix": false,
                "manufacturer_id": 15097,
                "stock": "В наличии"
            },
            {
                "id": 694565,
                "model": "CDSHIiP13Black",
                "sku": "CDSHIiP13Black",
                "name": "Чехол для смартфона Cosmic CD Shiny Magnetic for Apple iPhone 13 Black",
                "category_id": 508,
                "category_name": "Чехлы, накладки",
                "supl_price": 2.34,
                "price": 5.34,
                "margin": 3,
                "slug": "prod-chexol-dlya-smartfona-cosmic-cd-shiny-magnetic-for-694565",
                "image": "",
                "upc": "",
                "fix": false,
                "manufacturer_id": 15097,
                "stock": "В наличии"
            },
            {
                "id": 694564,
                "model": "CDMAGiP13PSilver",
                "sku": "CDMAGiP13PSilver",
                "name": "Чехол для смартфона Cosmic CD Magnetic for Apple iPhone 13 Pro Silver",
                "category_id": 508,
                "category_name": "Чехлы, накладки",
                "supl_price": 2.05,
                "price": 5.05,
                "margin": 3,
                "slug": "prod-chexol-dlya-smartfona-cosmic-cd-magnetic-for-apple-694564",
                "image": "",
                "upc": "",
                "fix": false,
                "manufacturer_id": 15097,
                "stock": "В наличии"
            },
            {
                "id": 694563,
                "model": "CosmicFGA14Green",
                "sku": "CosmicFGA14Green",
                "name": "Чехол для смартфона Cosmiс Full Case HQ 2mm for Samsung Galaxy A14 5G Green",
                "category_id": 508,
                "category_name": "Чехлы, накладки",
                "supl_price": 1.64,
                "price": 4.64,
                "margin": 3,
                "slug": "prod-chexol-dlya-smartfona-cosmis-full-case-hq-2mm-for--694563",
                "image": "",
                "upc": "",
                "fix": false,
                "manufacturer_id": 15097,
                "stock": "В наличии"
            },
            {
                "id": 694562,
                "model": "ClearColorXRN12PP5GTrBlue",
                "sku": "ClearColorXRN12PP5GTrBlue",
                "name": "Чехол для смартфона Cosmic Clear Color 2 mm for Xiaomi Redmi Note 12 Pro Plus 5G Transparent Blue",
                "category_id": 508,
                "category_name": "Чехлы, накладки",
                "supl_price": 1.3,
                "price": 4.3,
                "margin": 3,
                "slug": "prod-chexol-dlya-smartfona-cosmic-clear-color-2-mm-for--694562",
                "image": "",
                "upc": "",
                "fix": false,
                "manufacturer_id": 15097,
                "stock": "В наличии"
            },
            {
                "id": 694561,
                "model": "ClearColorXRN12P5GTrBlack",
                "sku": "ClearColorXRN12P5GTrBlack",
                "name": "Чехол для смартфона Cosmic Clear Color 2 mm for Xiaomi Redmi Note 12 Pro 5G Transparent Black",
                "category_id": 508,
                "category_name": "Чехлы, накладки",
                "supl_price": 1.3,
                "price": 4.3,
                "margin": 3,
                "slug": "prod-chexol-dlya-smartfona-cosmic-clear-color-2-mm-for--694561",
                "image": "",
                "upc": "",
                "fix": false,
                "manufacturer_id": 15097,
                "stock": "В наличии"
            },
            {
                "id": 694560,
                "model": "CosmicFXR12LavenderGrey",
                "sku": "CosmicFXR12LavenderGrey",
                "name": "Чехол для смартфона Cosmiс Full Case HQ 2mm for Xiaomi Redmi 12 Lavender Grey",
                "category_id": 508,
                "category_name": "Чехлы, накладки",
                "supl_price": 1.64,
                "price": 4.64,
                "margin": 3,
                "slug": "prod-chexol-dlya-smartfona-cosmis-full-case-hq-2mm-for--694560",
                "image": "",
                "upc": "",
                "fix": false,
                "manufacturer_id": 15097,
                "stock": "В наличии"
            },
            {
                "id": 694559,
                "model": "CoSoftPoXiR12cPink",
                "sku": "CoSoftPoXiR12cPink",
                "name": "Чехол для смартфона Cosmiс Soft Case Glass Cam for Xiaomi Redmi 12C Pink",
                "category_id": 508,
                "category_name": "Чехлы, накладки",
                "supl_price": 1.04,
                "price": 4.04,
                "margin": 3,
                "slug": "prod-chexol-dlya-smartfona-cosmis-soft-case-glass-cam-f-694559",
                "image": "",
                "upc": "",
                "fix": false,
                "manufacturer_id": 15097,
                "stock": "В наличии"
            },
            {
                "id": 694558,
                "model": "CDMAGS23Purple",
                "sku": "CDMAGS23Purple",
                "name": "Чехол для смартфона Cosmic CD Magnetic for Samsung S23 Purple",
                "category_id": 508,
                "category_name": "Чехлы, накладки",
                "supl_price": 2.05,
                "price": 5.05,
                "margin": 3,
                "slug": "prod-chexol-dlya-smartfona-cosmic-cd-magnetic-for-samsu-694558",
                "image": "",
                "upc": "",
                "fix": false,
                "manufacturer_id": 15097,
                "stock": "В наличии"
            },
            {
                "id": 694557,
                "model": "CDSHIiP14PMBlack",
                "sku": "CDSHIiP14PMBlack",
                "name": "Чехол для смартфона Cosmic CD Shiny Magnetic for Apple iPhone 14 Pro Max Black",
                "category_id": 508,
                "category_name": "Чехлы, накладки",
                "supl_price": 2.34,
                "price": 5.34,
                "margin": 3,
                "slug": "prod-chexol-dlya-smartfona-cosmic-cd-shiny-magnetic-for-694557",
                "image": "",
                "upc": "",
                "fix": false,
                "manufacturer_id": 15097,
                "stock": "В наличии"
            },
            {
                "id": 694556,
                "model": "CDSHIiP11Red",
                "sku": "CDSHIiP11Red",
                "name": "Чехол для смартфона Cosmic CD Shiny Magnetic for Apple iPhone 11 Red",
                "category_id": 508,
                "category_name": "Чехлы, накладки",
                "supl_price": 2.34,
                "price": 5.34,
                "margin": 3,
                "slug": "prod-chexol-dlya-smartfona-cosmic-cd-shiny-magnetic-for-694556",
                "image": "",
                "upc": "",
                "fix": false,
                "manufacturer_id": 15097,
                "stock": "В наличии"
            },
            {
                "id": 694555,
                "model": "CDSHIiP15DeepPurple",
                "sku": "CDSHIiP15DeepPurple",
                "name": "Чехол для смартфона Cosmic CD Shiny Magnetic for Apple iPhone 15 Deep Purple",
                "category_id": 508,
                "category_name": "Чехлы, накладки",
                "supl_price": 2.34,
                "price": 5.34,
                "margin": 3,
                "slug": "prod-chexol-dlya-smartfona-cosmic-cd-shiny-magnetic-for-694555",
                "image": "",
                "upc": "",
                "fix": false,
                "manufacturer_id": 15097,
                "stock": "В наличии"
            },
            {
                "id": 694554,
                "model": "CDSHIiP14PMGreen",
                "sku": "CDSHIiP14PMGreen",
                "name": "Чехол для смартфона Cosmic CD Shiny Magnetic for Apple iPhone 14 Pro Max Green",
                "category_id": 508,
                "category_name": "Чехлы, накладки",
                "supl_price": 2.34,
                "price": 5.34,
                "margin": 3,
                "slug": "prod-chexol-dlya-smartfona-cosmic-cd-shiny-magnetic-for-694554",
                "image": "",
                "upc": "",
                "fix": false,
                "manufacturer_id": 15097,
                "stock": "В наличии"
            },
            {
                "id": 694553,
                "model": "CDSHIiP11PDeepPurple",
                "sku": "CDSHIiP11PDeepPurple",
                "name": "Чехол для смартфона Cosmic CD Shiny Magnetic for Apple iPhone 11 Pro Deep Purple",
                "category_id": 508,
                "category_name": "Чехлы, накладки",
                "supl_price": 2.34,
                "price": 5.34,
                "margin": 3,
                "slug": "prod-chexol-dlya-smartfona-cosmic-cd-shiny-magnetic-for-694553",
                "image": "",
                "upc": "",
                "fix": false,
                "manufacturer_id": 15097,
                "stock": "В наличии"
            },
            {
                "id": 694552,
                "model": "CDMAGiP15PMDeepBlue",
                "sku": "CDMAGiP15PMDeepBlue",
                "name": "Чехол для смартфона Cosmic CD Magnetic for Apple iPhone 15 Pro Max Deep Blue",
                "category_id": 508,
                "category_name": "Чехлы, накладки",
                "supl_price": 2.05,
                "price": 5.05,
                "margin": 3,
                "slug": "prod-chexol-dlya-smartfona-cosmic-cd-magnetic-for-apple-694552",
                "image": "",
                "upc": "",
                "fix": false,
                "manufacturer_id": 15097,
                "stock": "В наличии"
            },
            {
                "id": 694430,
                "model": "Пружне тіло Для догляду і масажу 150 мл",
                "sku": "4823015937071",
                "name": "Масло для тела Зеленая Аптека Упругое тело Для ухода и массажа 150 мл (4823015937071)",
                "category_id": 1404,
                "category_name": "Для тела",
                "supl_price": 2.35,
                "price": 5.35,
                "margin": 3,
                "supl_id": 1,
                "slug": "prod-olya-dlya-tla-zelena-apteka-pruzhne-tlo-dlya-dogly-694430",
                "image": "",
                "uktz": "3304990000",
                "upc": "",
                "fix": false,
                "manufacturer_id": 14163,
                "stock": "Под заказ (1-3 дня)"
            }
        ]


}

const rootReducer = (state = initialState, action) => {

    switch (action.type) {
        // case SIMPLEHELLOWORLD:
        //     return [
        //         ...state,
        //         {
        //             title: action.payload.title,
        //             text: action.payload.text
        //         }
        //     ]
        default:
            return state;

    }

}


export default rootReducer